name: Deploy to Server

on:
  push:
    branches: [ main ]  # Or whatever your primary branch is named

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: davidobradovic/backofficetrebami:latest
          
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull davidobradovic/backofficetrebami:latest
            docker stop backofficetrebami || true
            docker rm backofficetrebami || true
            docker run -d --name backofficetrebami -p 6868:80 davidobradovic/backofficetrebami:latest